[package]
name = "basic"
version = "0.1.0"
edition = "2021"

# I need to make this a library
[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.2", features = ["extension-module"] }
 
